version: "3.7"

services:
  server:
    build: .
    env_file: .env.development
    volumes:
      - .:/usr/src/app
      - ./certs:/certs:ro

  dev-tls:
    build:
      context: .
      dockerfile: ./docker/dev-tls/Dockerfile
    depends_on:
      - server
    links:
      - server
    volumes:
#      - ./certs:/certs
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - target: 443
        published: 443
        protocol: tcp
